server:
  port: 8080

spring:
  application:
    name: aes-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/aes
    username: aes-manager
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /aes/swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG