openapi: 3.0.1
info:
  title: Формирование отчетов для AES и компонентов моделей и dto
  version: 1.0.0
tags:
  - name: AesApi

paths:
#  /attendance-data
  /attendance-data:
    post:
      tags:
        - AttendanceData
      description: Ввести данные за день
      operationId: addAttendanceData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'AttendanceDataDto.yaml#/components/schemas/AttendanceData'
      responses:
        200:
          description: Успешный вызов
          content:
            application/json:
              schema:
                $ref: 'AttendanceDataDto.yaml#/components/schemas/AttendanceDataDto'
        400:
          description: Некорректный по формату запрос
        500:
          description: Системная ошибка
    delete:
      tags:
        - AttendanceData
      description: Удалить все данные
      operationId: deleteAttendanceData
      responses:
        200:
          description: Успешный вызов
        400:
          description: Некорректный по формату запрос
        500:
          description: Системная ошибка
  /attendance-data/{id}:
    patch:
      tags:
        - AttendanceData
      description: Обновить данные за день
      operationId: updateAttendanceData
      parameters:
        - name: id
          description: Айди обновляемых данных
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'AttendanceDataDto.yaml#/components/schemas/AttendanceData'
      responses:
        200:
          description: Успешный вызов
          content:
            application/json:
              schema:
                $ref: 'AttendanceDataDto.yaml#/components/schemas/AttendanceDataDto'
        400:
          description: Некорректный по формату запрос
        500:
          description: Системная ошибка
    delete:
      tags:
        - AttendanceData
      description: Удалить данные по сотруднику
      operationId: deleteAttendanceDataById
      parameters:
        - name: id
          description: идентификатор данных посещаемости
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Успешный вызов
        400:
          description: Некорректный по формату запрос
        500:
          description: Системная ошибка
  /attendance-data/period:
    get:
      tags:
        - AttendanceData
      description: Получить данные за период
      operationId: getAttendanceDataByPeriod
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'CommonDto.yaml#/components/schemas/DateTimePeriod'
      responses:
        200:
          description: Успешный вызов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'AttendanceDataDto.yaml#/components/schemas/AttendanceDataDto'
        400:
          description: Некорректный по формату запрос
        500:
          description: Системная ошибка
    delete:
      tags:
        - AttendanceData
      description: Удалить данные за день
      operationId: deleteAttendanceDataByPeriod
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'CommonDto.yaml#/components/schemas/DateTimePeriod'
      responses:
        200:
          description: Успешный вызов
        400:
          description: Некорректный по формату запрос
        500:
          description: Системная ошибка
  /attendance-data/{employeeId}/period:
    get:
      tags:
        - AttendanceData
      description: Получить данные по сотруднику за период
      operationId: getAttendanceDataByPeriodByEmployee
      parameters:
        - name: employeeId
          description: Идентификатор сотрудника по которому надо получить данные
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'CommonDto.yaml#/components/schemas/DateTimePeriod'
      responses:
        200:
          description: Успешный вызов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'AttendanceDataDto.yaml#/components/schemas/AttendanceDataDto'
        400:
          description: Некорректный по формату запрос
        500:
          description: Системная ошибка
    delete:
      tags:
        - AttendanceData
      description: Удалить данные за день
      operationId: deleteAttendanceDataByPeriodByEmployee
      parameters:
        - name: employeeId
          description: Идентификатор сотрудника по которому надо получить данные
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'CommonDto.yaml#/components/schemas/DateTimePeriod'
      responses:
        200:
          description: Успешный вызов
        400:
          description: Некорректный по формату запрос
        500:
          description: Системная ошибка
  /attendance-data/{departmentId}/period:
    get:
      tags:
        - AttendanceData
      description: Получить данные по сотруднику за период
      operationId: getAttendanceDataByDepartmentByPeriod
      parameters:
        - name: departmentId
          description: Идентификатор отдела по которому надо получить данные
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'CommonDto.yaml#/components/schemas/DateTimePeriod'
      responses:
        200:
          description: Успешный вызов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'AttendanceDataDto.yaml#/components/schemas/AttendanceDataDto'
        400:
          description: Некорректный по формату запрос
        500:
          description: Системная ошибка

#  /work-schedules:
#    post:
#      tags:
#        - WorkSchedule
#      description: Добавить график в БД
#      operationId: addSchedule
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              $ref: 'WorkScheduleDto.yaml#/components/schemas/WorkSchedule'
#      responses:
#        200:
#          description: Успешный вызов
#          content:
#            application/json:
#              schema:
#                $ref: 'WorkScheduleDto.yaml#/components/schemas/WorkScheduleDto'
#        400:
#          description: Некорректный по формату запрос
#        500:
#          description: Системная ошибка

#  /kpis:
#    post:
#      tags:
#        - Kpi
#      description: Добавить kpi в БД
#      operationId: addKpi
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              $ref: "#/components/schemas/WorkSchedule"
#      responses:
#        200:
#          description: Успешный вызов
#          content:
#            application/json:
#              schema:
#                $ref: "#/components/schemas/WorkScheduleDto"
#        400:
#          description: Некорректный по формату запрос
#        500:
#          description: Системная ошибка