openapi: 3.0.1
info:
  title: Формирование моделей и dto для AES
  version: 1.0.0

paths: { }

components:
  schemas:

    DateTimePeriod:
      type: object
      properties:
        begin:
          description: Дата начала периода
          type: string
          format: date-time
        end:
          description: Дата окончания периода
          type: string
          format: date-time