openapi: 3.0.1
info:
  title: Формирование моделей и DTO для AES
  version: 1.0.0

paths: {}

components:
  schemas:
    # Общие свойства сотрудника
    EmployeeBase:
      type: object
      properties:
        id:
          description: ID записи
          type: integer
          format: int64
        lastName:
          description: Фамилия сотрудника
          type: string
        firstName:
          description: Имя сотрудника
          type: string
        middleName:
          description: Отчество сотрудника
          type: string
        phone:
          description: Номер телефона сотрудника
          type: string
        email:
          description: Email сотрудника
          type: string
        department:
          description: Департамент сотрудника
          $ref: 'DepartmentDto.yaml#/components/schemas/Department'
        position:
          description: Должность сотрудника
          type: string
        workSchedule:
          description: График работы
          $ref: 'WorkScheduleDto.yaml#/components/schemas/WorkSchedule'
        dateOfAdmission:
          description: Дата трудоустройства
          type: string
          format: date
          example: 2000-01-01
        dateOfDismissal:
          description: Дата увольнения
          type: string
          format: date
          example: 2000-01-01
        jobStatus:
          description: Рабочий статус
          $ref: '#/components/schemas/JobStatus'

    # Модель сотрудника
    Employee:
      allOf:
        - $ref: '#/components/schemas/EmployeeBase'
        - type: object
          description: Полная модель сотрудника

    # DTO сотрудника
    EmployeeDto:
      allOf:
        - $ref: '#/components/schemas/EmployeeBase'
        - type: object
          description: DTO сотрудника

    JobStatus:
      type: string
      enum:
        - New
        - Working
        - Fired
      description: Статус сотрудника в организации